version: '3.8'

services:
  flyclim-web:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - MONGODB_URI=${MONGODB_URI}
        - NEXTAUTH_URL=${NEXTAUTH_URL}
        - NEXTAUTH_SECRET=${NEXTAUTH_SECRET}
        - NEXT_PUBLIC_METADATA_BASE=${NEXT_PUBLIC_METADATA_BASE}
        - OPENAI_API_KEY=${OPENAI_API_KEY}
        - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
        - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
        - GOOGLE_PROJECT_ID=${GOOGLE_PROJECT_ID}
        - GOOGLE_AUTH_URI=${GOOGLE_AUTH_URI}
        - GOOGLE_TOKEN_URI=${GOOGLE_TOKEN_URI}
        - GOOGLE_AUTH_PROVIDER_CERT_URL=${GOOGLE_AUTH_PROVIDER_CERT_URL}
        - LINKEDIN_CLIENT_ID=${LINKEDIN_CLIENT_ID}
        - LINKEDIN_ACCESS_TOKEN=${LINKEDIN_ACCESS_TOKEN}
        - LINKEDIN_ORGANIZATION_ID=${LINKEDIN_ORGANIZATION_ID}
        - LINKEDIN_REDIRECT_URI=${LINKEDIN_REDIRECT_URI}
    container_name: flyclim-website
    restart: unless-stopped
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=production
      - PORT=3001
    env_file:
      - .env.local
    networks:
      - flyclim-network
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:3001"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

networks:
  flyclim-network:
    driver: bridge
