version: '3.8'

services:
  flyclim-web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: flyclim-website
    restart: unless-stopped
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=production
      - PORT=3001
    env_file:
      - .env.local
    networks:
      - flyclim-network
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:3001"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

networks:
  flyclim-network:
    driver: bridge
